### ISSUE TITLE
Missing `supported_currencies` helper

### ISSUE THREAD

**Issue by joshnuss** [renuo/spree-sale-prices#1]
Hi!

When I visit the sales prices page in admin, get an error about supported_currencies not found:

```
NameError: undefined local variable or method `supported_currencies' for #<#<Class:0x00000009804ab8>:0x000000097e78f0>
  spree/base_helper.rb:161:in `method_missing'
```

Is there a dependency on spree_multi_currency?

**Comment by schmijos** [comment]
Thx for the hint. I thought it would use `Spree::CurrencyHelpers.supported_currencies` but maybe my IDE was misleading me.

**Update:**
It is using `Spree::CurrencyHelpers.supported_currencies` but this method is from _spree_multi_currency_

**Comment by schmijos** [comment]
Has been fixed for _2-4-stable_ and _3-0-stable_

**Comment by joshnuss** [comment]
Thanks!!
